title: KangNaewon's Blog
author:
  name: KangNaewon
description: >-
  Welcome to my new blog.

remote_theme: "abhinavs/moonwalk"

theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "Home"
  date_format: "%Y-%m-%d"
  show_description: true
